# Install these with
# uv add --dev pytest

[project]
name = "my-fastapi-app" # Replace with your project name
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "google-auth",
    "google-auth-oauthlib",
    "google-auth-httplib2",
    "google-api-python-client",
    "websockets",
    "httpx",
    "jinja2",
    "fastapi",
    "fastapi[standard]",
    "uvicorn",
    "python-dotenv", # If you're using it for environment variables
    # Add all your direct top-level production dependencies here
    "anyio>=4.9.0",
    "click>=8.2.1",
    "unicorn>=2.1.3",
    "pydantic>=2.11.7",
]

[build-system]
requires = ["setuptools>=61.0"] # Or another build backend
build-backend = "setuptools.build_meta"

# This section is for development-specific dependencies,
# adhering to the new [dependency-groups] standard.
[dependency-groups]
dev = [
    "ruff",
    "ruff-lsp",
    "pytest",
    "pytest-env",
    "pytest-cov",
    "pytest-asyncio",
    "coverage",   # Often used with pytest-cov, so keep it here
    "livereload", # Only for development
]

[tool.setuptools.packages.find]
where = ["."]
include = ["myapp*"]

[tool.ruff]
exclude = ["lib/"]
