install:
	sudo cp air_basistech_net.service slg1_basistech_net.service /etc/systemd/system/
	sudo systemctl daemon-reload
	sudo systemctl restart slg1_basistech_net.service
	sudo systemctl restart air_basistech_net.service
