# Type Path                                         Mode User Group Age Argument
d      /run/lock/temperature-bot                    0755 root root  -   -
f      /run/lock/temperature-bot/ae200.lock         0444 root root  -   -
